documentation:
  - documentation/*
  - documentation/**/*
  - ./README.md
  - use-shopping-cart/README.md

example: examples/**/*

package:
  - use-shopping-cart/*
  - use-shopping-cart/**/*

tests:
  - use-shopping-cart/**/*.test.*


