[build]
  command = "yarn workspace use-shopping-cart build && yarn workspace documentation build"
  publish = "documentation/public"
  functions = "examples/cra/functions"

[dev]
  port = 8888
  command = "yarn cra-dev"
  targetPort = 3000
  framework = "#custom"

[[redirects]]
  from = "https://use-shopping-cart.netlify.app"
  to = "https://useshoppingcart.com"
  status = 301
